services:

  nginx:
    container_name: nginx-balancer
    build:
      context: ../.
      dockerfile: build/nginx.Dockerfile
    depends_on:
      - urler-1
      - urler-2
    ports:
      - "5100:5100"
      - "8080:8080"
      - "8000:8000"
    restart: always

  urler-1:
   image: urler:latest
   container_name: urler-1
   restart: always
   depends_on:
     - urls-tnt
     - queue-tnt
   ports:
     - 8081:8080
     - 8001:8000
   volumes:
     - type: bind
       source: ../urler/env/compose/config.yaml
       target: /etc/urler/config.yaml
   build:
     dockerfile: build/urler.Dockerfile
     context: ../.

  urler-2:
   image: urler:latest
   container_name: urler-2
   restart: always
   depends_on:
     - urls-tnt
     - queue-tnt
   ports:
     - 8082:8080
     - 8002:8000
   volumes:
     - type: bind
       source: ../urler/env/compose/config.yaml
       target: /etc/urler/config.yaml
   build:
     dockerfile: build/urler.Dockerfile
     context: ../.

  qrer:
   image: qrer:latest
   container_name: qrer
   restart: always
   depends_on:
     - urls-tnt
     - queue-tnt
   volumes:
     - type: bind
       source: ../qrer/env/compose/config.yaml
       target: /etc/qrer/config.yaml
   build:
     dockerfile: build/qrer.Dockerfile
     context: ../.

  notifier:
   image: notifier:latest
   container_name: notifier
   restart: always
   depends_on:
     - queue-tnt
   volumes:
     - type: bind
       source: ../notifier/env/compose/config.yaml
       target: /etc/notifier/config.yaml
   build:
     dockerfile: build/notifier.Dockerfile
     context: ../.

  urls-tnt:
    image: urls-tnt:latest
    container_name: urls-tnt
    restart: always
    ports:
      - 3301:3301
      - 3303:3303
    volumes:
      - ./data/urls-tnt-data:/var/lib/tarantool
    environment:
      TARANTOOL_LISTEN: 0.0.0.0:3301
      TARANTOOL_WAL_DIR: /var/lib/tarantool
      TARANTOOL_MEMTX_DIR: /var/lib/tarantool
      TARANTOOL_VINYL_DIR: /var/lib/tarantool
      TARANTOOL_ADMIN_ADDR: 0.0.0.0:3303
      USER_PASS: dev
    build:
      dockerfile: build/urls-tnt.Dockerfile
      context: ../.

  queue-tnt:
    image: queue-tnt:latest
    container_name: queue-tnt
    restart: always
    ports:
      - 3401:3301
      - 3403:3303
    volumes:
      - ./data/queue-tnt-data:/var/lib/tarantool
    environment:
      TARANTOOL_LISTEN: 0.0.0.0:3301
      TARANTOOL_WAL_DIR: /var/lib/tarantool
      TARANTOOL_MEMTX_DIR: /var/lib/tarantool
      TARANTOOL_VINYL_DIR: /var/lib/tarantool
      TARANTOOL_ADMIN_ADDR: 0.0.0.0:3303
      USER_PASS: dev
    build:
      dockerfile: build/queue-tnt.Dockerfile
      context: ../.