services:

  urler:
   image: urler:latest
   container_name: urler
   restart: always
   depends_on:
     - urls-tnt
     - queue-tnt
   ports:
     - 8080:8080
     - 8000:8000
   volumes:
     - type: bind
       source: ../urler/env/compose/config.yaml
       target: /etc/urler/config.yaml
   build:
     dockerfile: build/urler.Dockerfile
     context: ../.

  # qrer:
  #  image: qrer:latest
  #  container_name: qrer
  #  restart: always
  #  depends_on:
  #    - urls-tnt
  #    - queue-tnt
  #  volumes:
  #    - type: bind
  #      source: ../qrer/env/compose/config.yaml
  #      target: /etc/qrer/config.yaml
  #  build:
  #    dockerfile: build/qrer.Dockerfile
  #    context: ../.

  urls-tnt:
    image: urls-tnt:latest
    container_name: urls-tnt
    restart: always
    ports:
      - 3301:3301
      - 3303:3303
    volumes:
      - ./data/urls-tnt-data:/var/lib/tarantool
    environment:
      TARANTOOL_LISTEN: 0.0.0.0:3301
      TARANTOOL_WAL_DIR: /var/lib/tarantool
      TARANTOOL_MEMTX_DIR: /var/lib/tarantool
      TARANTOOL_VINYL_DIR: /var/lib/tarantool
      TARANTOOL_ADMIN_ADDR: 0.0.0.0:3303
      USER_PASS: dev
    build:
      dockerfile: build/urls-tnt.Dockerfile
      context: ../.

  queue-tnt:
    image: queue-tnt:latest
    container_name: queue-tnt
    restart: always
    ports:
      - 3401:3301
      - 3403:3303
    volumes:
      - ./data/queue-tnt-data:/var/lib/tarantool
    environment:
      TARANTOOL_LISTEN: 0.0.0.0:3301
      TARANTOOL_WAL_DIR: /var/lib/tarantool
      TARANTOOL_MEMTX_DIR: /var/lib/tarantool
      TARANTOOL_VINYL_DIR: /var/lib/tarantool
      TARANTOOL_ADMIN_ADDR: 0.0.0.0:3303
      USER_PASS: dev
    build:
      dockerfile: build/queue-tnt.Dockerfile
      context: ../.