env: "devel"

urls_tnts:
  - urls_tnt:
    address: "localhost:3401"
    reconnect: 5
    reconnects: 5
    user: "urls_user"
    password: "dev"
  - urls_tnt:
    address: "localhost:3402"
    reconnect: 5
    reconnects: 5
    user: "urls_user"
    password: "dev"
  - urls_tnt:
    address: "localhost:3403"
    reconnect: 5
    reconnects: 5
    user: "urls_user"
    password: "dev"

qr_tnt:
  address: "localhost:3401"
  reconnect: 5
  reconnects: 5
  user: "q_user"
  password: "dev"
  timeout: 2
  prior: 0
  ttl: 0
  delay: 0
  ttr: 300

metrics:
  address: ":8880"