env: "devel"

grpc_server:
  address: ":8080"

http_server:
  address: ":8000"

urls_tnt:
  address: "localhost:3301"
  reconnect: 5
  reconnects: 5
  user: "urls_user"
  password: "dev"

qr_tnt:
  address: "localhost:3401"
  reconnect: 5
  reconnects: 5
  user: "qr_user"
  password: "dev"
  prior: 0
  ttl: 0
  delay: 0
  ttr: 300