env: "devel"
host: "localhost"

grpc_server:
  address: ":8088"

http_server:
  address: ":8008"

urls_tnt:
  address: "localhost:3301"
  reconnect: 5
  reconnects: 5
  user: "urls_user"
  password: "dev"

qr_tnt:
  address: "localhost:3401"
  reconnect: 5
  reconnects: 5
  user: "q_user"
  password: "dev"
  prior: 0
  ttl: 0
  delay: 0
  ttr: 300

metrics:
  address: ":8888"