env: "devel"

urls_tnt:
  address: "urls-tnt-m:3301"
  reconnect: 5
  reconnects: 5
  user: "urls_user"
  password: "dev"

qr_tnt:
  address: "queue-tnt:3301"
  reconnect: 5
  reconnects: 5
  user: "q_user"
  password: "dev"
  timeout: 2
  prior: 0
  ttl: 0
  delay: 0
  ttr: 300

metrics:
  address: ":8880"